package com.halitozgur.lablog.controller;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import com.halitozgur.lablog.model.Personnel;

/**
 * Login controller that defines paths to login, register, and home page
 * @author User
 *
 */
@Controller
public class LoginController {
	

	/**
	 * returns index.html
	 * @return
	 */
	@GetMapping("/home")
	public String index() {
		return "index";
	}
	
	/**
	 * returns the login page auto generated by spring security.
	 * @return
	 */
	@GetMapping("/login")
	public String login() {
		return "login";
	}
	
	/**
	 * Creates a new personnel, adds it to the model, and returns register.html
	 * @param model
	 * @return
	 */
	@GetMapping("/register")
	public String register(Model model) {
		Personnel personnel = new Personnel();
		model.addAttribute("personnel", personnel);
		return "register";
	}
	
	
	
}
